Controllers/VolunteerController.cs
using Microsoft.EntityFrameworkCore;
using AuthSystem.Areas.Identity.Data;
using AuthSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;



namespace AuthSystem.Controllers
{
    public class VolunteerController : Controller
    {
        private readonly ApplicationDbContext _db;

        public VolunteerController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string status, string option, string searchTerm)
        {

            // Sorts results based on search term in the column specified by 'option'
            switch (option)
            {
                case "reset":
                    return View(_db.VolunteerList.ToList());
                case "first-name":
                    return View(_db.VolunteerList.Where(x => x.FirstName == searchTerm || searchTerm == null).ToList());
                case "last-name":
                    return View(_db.VolunteerList.Where(x => x.LastName == searchTerm || searchTerm == null).ToList());
                case "center-preference":
                    return View(_db.VolunteerList.Where(x => x.OpportunityCenterPreference.Contains(searchTerm) || searchTerm == null).ToList());
                default:
                    break;
            }

            // Sorts results based on approval status
            switch (status)
            {
                case "approved-pending":
                    return View(_db.VolunteerList.Where(x => x.ApprovalStatus == "Approved" || x.ApprovalStatus == "Pending").ToList());
                case "approved":
                    return View(_db.VolunteerList.Where(x => x.ApprovalStatus == "Approved").ToList());
                case "pending":
                    return View(_db.VolunteerList.Where(x => x.ApprovalStatus == "Pending").ToList());
                case "disapproved":
                    return View(_db.VolunteerList.Where(x => x.ApprovalStatus == "Disapproved").ToList());
                case "inactive":
                    return View(_db.VolunteerList.Where(x => x.ApprovalStatus == "Inactive").ToList());
                case "all":
                    return View(_db.VolunteerList.ToList());
                default:
                    break;
            }

            return View(_db.VolunteerList.ToList());
               
        }

        //This method leads you to the page that allows you to add new volunteers
        public IActionResult AddVolunteer()
        {
            return View();
        }

        //This method will actually add the new volunteer to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddVolunteer(VolunteerList vol)
        {
            if (ModelState.IsValid)
            {
                _db.VolunteerList.Add(vol);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vol);
        }

        //This method leads you to the page that allows you to edit the volunteers
        public IActionResult EditVolunteer(int? Id)
        {

            if (Id == 0)
            {
                return NotFound();
            }

            var obj = _db.VolunteerList.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        //This method will update the edit made to the volunteer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditVolunteer(VolunteerList vol)
        {
            if (ModelState.IsValid)
            {
                _db.VolunteerList.Update(vol);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vol);
        }

        public IActionResult DeleteVolunteer(int? Id)
        {

            if (Id == 0)
            {
                return NotFound();
            }

            var obj = _db.VolunteerList.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        //This method will update the database by deleting the entity
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteVolunteerEntity(int? Id)
        {
            var entity = _db.VolunteerList.Find(Id);
            _db.VolunteerList.Remove(entity);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Views/Volunteer/AddVolunteer.cshtml
@model VolunteerList


<form method="post" asp-action="AddVolunteer">
    <div class="border p-5">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <h2 class="text-info">Add New Volunteer</h2>
        </div>
        <br />
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Username"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Username" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Password"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Password" type="password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="OpportunityCenterPreference"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityCenterPreference" class="form-control" />
                        <span asp-validation-for="OpportunityCenterPreference" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="SkillsInterests"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="SkillsInterests" class="form-control" />
                        <span asp-validation-for="SkillsInterests" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Availability"></label>
                    </div>
                    <div class="col-8">
                        <input id="availabilityVolunteer" asp-for="Availability" class="form-control" pattern="^[a-zA-Z]+(,[a-zA-Z]+)*$" placeholder="M,W,F"/>
                        <span asp-validation-for="Availability" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Address"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Phonenumber"></label>
                    </div>
                    <div class="col-8">
                        <input pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" asp-for="Phonenumber" class="form-control" />
                        <span asp-validation-for="Phonenumber" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Email"></label>
                    </div>
                    <div class="col-8">
                        <input type="email" asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="EducationBackground"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EducationBackground" class="form-control" />
                        <span asp-validation-for="EducationBackground" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="License"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="License" class="form-control" />
                        <span asp-validation-for="License" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="EmergencyContactName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EmergencyContactName" class="form-control" />
                        <span asp-validation-for="EmergencyContactName" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="EmergencyContactNumber"></label>
                    </div>
                    <div class="col-8">
                        <input pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" asp-for="EmergencyContactNumber" class="form-control" />
                        <span asp-validation-for="EmergencyContactNumber" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="EmergencyContactEmail"></label>
                    </div>
                    <div class="col-8">
                        <input type="email" asp-for="EmergencyContactEmail" class="form-control" />
                        <span asp-validation-for="EmergencyContactEmail" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="EmergencyContactAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EmergencyContactAddress" class="form-control" />
                        <span asp-validation-for="EmergencyContactAddress" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="DriversLicenseAvailable"></label>
                    </div>
                    <div class="col-8">
                        <input type="checkbox" asp-for="DriversLicenseAvailable" class="form-check" />
                        <span asp-validation-for="DriversLicenseAvailable" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="SocialSecurityAvailable"></label>
                    </div>
                    <div class="col-8">
                        <input type="checkbox" asp-for="SocialSecurityAvailable" class="form-check" />
                        <span asp-validation-for="SocialSecurityAvailable" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="ApprovalStatus"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="ApprovalStatus" class="form-select">
                            <option value="" selected disabled>Select one...</option>
                            <option value="Approved">Approved</option>
                            <option value="Pending">Pending</option>
                            <option value="Disapproved">Disapproved</option>
                            <option value="Inactive">Inactive</option>

                        </select>
                        <span asp-validation-for="ApprovalStatus" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-primary w-100" value="Add" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">

            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Volunteer/DeleteVolunteer.cshtml
@model VolunteerList

<form method="post" asp-action="DeleteVolunteerEntity">
    <input asp-for="Id" hidden />
    <div class="border p-5">
        <div class="row">
            <h2 class="text-info">Delete Volunteer</h2>
        </div>
        <br />
        <div class="row">
            <div class="col-8">
                <div class="row">
                    <div class="col-4">
                        <label asp-for="Username"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Username" disabled class="form-control" />

                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-4">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" disabled class="form-control" />

                    </div>

                </div>
                <br />

                <div class="row">
                    <div class="col-4">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" disabled class="form-control" />

                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">

            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

} 

Views/Volunteer/EditVolunteer.cshtml
@model VolunteerList


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-5">
        <div class="row">
            <h2 class="text-info">Edit Volunteer</h2>
        </div>
        <br />
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <label asp-for="FirstName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="LastName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="Username"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Username" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="Password"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="OpportunityCenterPreference"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityCenterPreference" class="form-control" />
                        <span asp-validation-for="OpportunityCenterPreference" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="SkillsInterests"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="SkillsInterests" class="form-control" />
                        <span asp-validation-for="SkillsInterests" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="Availability"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Availability" class="form-control" />
                        <span asp-validation-for="Availability" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="Address"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="Phonenumber"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Phonenumber" class="form-control" />
                        <span asp-validation-for="Phonenumber" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="Email"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="EducationBackground"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EducationBackground" class="form-control" />
                        <span asp-validation-for="EducationBackground" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="License"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="License" class="form-control" />
                        <span asp-validation-for="License" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="EmergencyContactName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EmergencyContactName" class="form-control" />
                        <span asp-validation-for="EmergencyContactName" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="EmergencyContactNumber"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EmergencyContactNumber" class="form-control" />
                        <span asp-validation-for="EmergencyContactNumber" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="EmergencyContactEmail"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EmergencyContactEmail" class="form-control" />
                        <span asp-validation-for="EmergencyContactEmail" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="EmergencyContactAddress"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EmergencyContactAddress" class="form-control" />
                        <span asp-validation-for="EmergencyContactAddress" class="text-danger"></span>
                    </div>

                </div>
<br />
                <div class="row">
                    <div class="col">
                        <label asp-for="DriversLicenseAvailable"></label>
                    </div>
                    <div class="col-8">
                        <input type="checkbox" asp-for="DriversLicenseAvailable" class="form-check" />
                        <span asp-validation-for="DriversLicenseAvailable" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="SocialSecurityAvailable"></label>
                    </div>
                    <div class="col-8">
                        <input type="checkbox" asp-for="SocialSecurityAvailable" class="form-check" />
                        <span asp-validation-for="SocialSecurityAvailable" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label asp-for="ApprovalStatus"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ApprovalStatus" class="form-control" />
                        <span asp-validation-for="ApprovalStatus" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-primary w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">

            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Volunteer/Index.cshtml
@model IEnumerable<VolunteerList>


<h1>Manage Volunteers</h1>

<div class="container p-5">
    @if (Model.Count() > 0)
    {
        <div class="row p-3">
            <div class="col">
                <h2 class="text-primary">Volunteer List</h2>
            </div>
            <div class="col text-right">
                <a asp-controller="Volunteer" asp-action="AddVolunteer" class="btn btn-primary">Add New Volunteer</a>
            </div>
        </div>
    }

    <br />

    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
                <table class="table table-bordered" id="volunteer-table" style="width:100%">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Opportunity Center Preference</th>
                            <th>Approval Status</th>
                            <th>Availability</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var obj in Model)
                        {
                            <tr>
                                <td>@obj.FirstName</td>
                                <td>@obj.LastName</td>
                                <td>@obj.OpportunityCenterPreference</td>
                                <td>@obj.ApprovalStatus</td>
                                <td>@obj.Availability</td>
                                <td class="w-25 text-center">
                                    <div class="btn-group" role="group">
                                        <a asp-controller="Volunteer" asp-route-Id="@obj.Id" asp-action="EditVolunteer" class="btn btn-outline-primary">Edit</a>
                                        <a asp-controller="Volunteer" asp-route-Id="@obj.Id" asp-action="DeleteVolunteer" class="btn btn-outline-danger">Delete</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No results were found for that search term.</p>
            }
        </div>
        <div class="col">

            <div class="search-container input-group my-2">
                <form asp-controller="Volunteer" asp-action="Index" class="form-inline">
                    <label for="search-title" class="pr-2 mb-3">Search by:</label>
                    <select name="option">
                        <option value="first-name">First Name</option>
                        <option value="last-name">Last Name</option>
                        <option value="center-preference">Center Preference</option>
                    </select>
                    <div class="input-group mb-2">
                        <input type="search" class="form-control" placeholder="Search..." name="searchTerm">
                        <input type="submit" value="Filter" class="btn btn-primary my-2 my-sm-0" name="Search" />
                    </div>
                </form>
            </div>



            <div class="input-group mb-2">

                @using (Html.BeginForm())
                {
                    <select name="status">
                        <option value="approved-pending">Approved/Pending</option>
                        <option value="approved">Approved</option>
                        <option value="pending">Pending</option>
                        <option value="disapproved">Disapproved</option>
                        <option value="inactive">Inactive</option>
                        <option value="all">All</option>
                    </select>
                    <input type="submit" value="Search" class="btn btn-primary" name="Filter" />
                }
            </div>
            <a asp-controller="Home" asp-action="VolunteerOpportunityMatches" class="btn btn-primary">View Volunteer Opportunity Matches</a>

                @using (Html.BeginForm())
                {
                    <button type="submit" class="btn btn-danger my-3" value="reset" name="option">Reset Filters</button>
                }
        </div>
    </div>
</div>