Controllers/OpportunityController.cs
using AuthSystem.Areas.Identity.Data;
using AuthSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace AuthSystem.Controllers
{
    public class OpportunityController : Controller
    {
        private readonly ApplicationDbContext _db;

        public OpportunityController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(string searchTerm, string center, string date, string option)
        {
            DateTime currTime = DateTime.Now;
            DateTime recentDate = DateTime.Now.AddDays(-60);



            // Populates dropdown in view
            ViewBag.Center = (from o in _db.OpportunityList
                              select o.OpportunityCenter).Distinct();

            // Handles search bar logic
            switch (option)
            {
                case "reset":
                    return View(_db.OpportunityList.ToList());
                case "title":
                    return View(_db.OpportunityList.Where(x => x.OpportunityTitle.Contains(searchTerm) || searchTerm == null).ToList());
                case "center":
                    return View(_db.OpportunityList.Where(x => x.OpportunityCenter.Contains(searchTerm) || searchTerm == null).ToList());
                case "days-open":
                    return View(_db.OpportunityList.Where(x => x.Availability.Contains(searchTerm) || searchTerm == null).ToList());
                default:
                    break;
            }


            // If date is true, filter opportunities by the last 60 days
            if (date == "true")
            {
                var filteredOpportunity = from o in _db.OpportunityList
                                          orderby o.DateAdded
                                          where o.DateAdded <= currTime && o.DateAdded >= recentDate
                                          select o;
                return View(filteredOpportunity);

            }

            // If date is not specified, filter opportunities based on default or dropdown
            else
            {
                var opportunities = from o in _db.OpportunityList
                                    orderby o.OpportunityTitle
                                    where o.OpportunityCenter.Contains(center) || center == null || center == ""
                                    select o;
                return View(opportunities.ToList());
            }
        }



        //This method leads you to the page that allows you to add new opportunities
        public IActionResult AddOpportunity()
        {
            return View();
        }

        //This method will actually add the new opportunity to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddOpportunity(OpportunityList opp)
        {
            if (ModelState.IsValid)
            {
                _db.OpportunityList.Add(opp);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(opp);
        }

        //This method leads you to the page that allows you to edit the opportunities
        public IActionResult EditOpportunity(int? Id)
        {

            if (Id == 0)
            {
                return NotFound();
            }

            var obj = _db.OpportunityList.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        //This method will update the edit made to the opportunity
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditOpportunity(OpportunityList opp)
        {
            if (ModelState.IsValid)
            {
                _db.OpportunityList.Update(opp);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(opp);
        }

        //This method will get the specific entity that needs to be deleted
        public IActionResult DeleteOpportunity(int? Id)
        {

            if (Id == 0)
            {
                return NotFound();
            }

            var obj = _db.OpportunityList.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        //This method will update the database by deleting the entity
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteOpportunityEntity(int? Id)
        {
            var entity = _db.OpportunityList.Find(Id);
            _db.OpportunityList.Remove(entity);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

Views/Opportunity/AddOpportunity.cshtml
@model OpportunityList


<form method="post" asp-action="AddOpportunity">
    <div class="border p-5">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <h2 class="text-info">Add New Opportunity</h2>
        </div>
        <br />
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="OpportunityCenter"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityCenter" class="form-control" />
                        <span asp-validation-for="OpportunityCenter" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="OpportunityTitle"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityTitle" class="form-control" />
                        <span asp-validation-for="OpportunityTitle" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="DateAdded"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DateAdded" class="form-control" />
                        <span asp-validation-for="DateAdded" class="text-danger"></span>
                    </div>
                </div>
                <br />

                <div class="row">
                    <div class="col">
                        <label class="required" asp-for="Availability"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Availability" class="form-control" pattern="^[a-zA-Z]+(,[a-zA-Z]+)*$" placeholder="M,T,W,R,F,Sa,Su"/>

                        <span asp-validation-for="Availability" class="text-danger"></span>
                        <small>Please separate values by commas</small>
                    </div>
                </div>
                <br />
                <div class="row">

                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-primary w-100" value="Add" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Opportunity/DeleteOpportunity.cshtml
@model OpportunityList


<form method="post" asp-action="DeleteOpportunityEntity">
    <input asp-for="Id" hidden/>
    <div class="border p-5">
        <div class="row">
            <h2 class="text-info">Delete Opportunity</h2>
        </div>
        <br />
        <div class="row">
            <div class="col-8">
                <div class="row">
                    <div class="col-4">
                        <label asp-for="OpportunityCenter"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityCenter" disabled class="form-control" />

                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-4">
                        <label asp-for="OpportunityTitle"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityTitle" disabled class="form-control" />

                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">

            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Opportunity/EditOpportunity.cshtml
@model OpportunityList


<form method="post">
    <input asp-for="Id" hidden/>
    <div class="border p-5">
        <div class="row">
            <h2 class="text-info">Edit Opportunity</h2>
        </div>
        <br />
        <div class="row">
            <div class="col-8">
                <div class="row">
                    <div class="col-4">
                        <label asp-for="OpportunityCenter"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityCenter" class="form-control" />
                        <span asp-validation-for="OpportunityCenter" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-4">
                        <label asp-for="OpportunityTitle"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="OpportunityTitle" class="form-control" />
                        <span asp-validation-for="OpportunityTitle" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">
                    <div class="col-4">
                        <label asp-for="DateAdded"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DateAdded" class="form-control" />
                        <span asp-validation-for="DateAdded" class="text-danger"></span>
                    </div>

                </div>
                <br />

                <div class="row">
                    <div class="col-4">
                        <label asp-for="Availability"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Availability" class="form-control" />
                        <span asp-validation-for="Availability" class="text-danger"></span>
                    </div>

                </div>
                <br />

                <div class="row">
                    <div class="col offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-primary w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">

            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Views/Opportunity/Index.cshtml
@model IEnumerable<OpportunityList>

<h1>Manage Opportunities</h1>

<div class="container p-5">
    @if (Model.Count() > 0)
    {
<div class="row p-3">
    <div class="col">
        <h2 class="text-primary">Opportunity List</h2>
    </div>
    <div class="col text-right">
        <a asp-controller="Opportunity" asp-action="AddOpportunity" class="btn btn-primary">Add New Opportunity</a>
    </div>
</div>}

    <br />

    <div class="row">
        <div class="col">
            @if (Model.Count() > 0)
            {
<table class="table table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Title</th>
            <th>Center</th>
            <th>Date Added</th>
            <th>Days Open</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
<tr>
    <td>@obj.OpportunityTitle</td>
    <td>@obj.OpportunityCenter</td>
    <td>@obj.DateAdded.ToShortDateString()</td>
    <td>@obj.Availability</td>
    <td class="w-25 text-center">
        <div class="btn-group" role="group">
            <a asp-controller="Opportunity" asp-route-Id="@obj.Id" asp-action="EditOpportunity" class="btn btn-outline-primary">Edit</a>
            <a asp-controller="Opportunity" asp-route-Id="@obj.Id" asp-action="DeleteOpportunity" class="btn btn-outline-danger">Delete</a>
        </div>
    </td>
</tr>
}
    </tbody>
</table> }
else
{
<p>No results were found for that search term.</p>}
        </div>
        <div class="col">
            <div class="search-container input-group my-2">
                <form asp-controller="Opportunity" asp-action="Index" class="form-inline">
                    <label for="search-title" class="pr-2 mb-3">Search by:</label>
                    <select name="option">
                        <option value="title">Title</option>
                        <option value="center">Center</option>
                        <option value="days-open">Days Open</option>
                    </select>

                    <div class="input-group mb-2">
                            <input type="search" class="form-control" placeholder="Search..." name="searchTerm">
                            <input type="submit" value="Filter" class="btn btn-primary my-2 my-sm-0" name="Search" />
                    </div>
                </form>
            </div>

        <div class="input-group mb-2">
        @using (Html.BeginForm())
        {
            <span class="mr-2">Filter by Center: </span>@Html.DropDownList("center", new SelectList(ViewBag.Center))
                <input type="submit" value="Search" class="btn btn-primary" />
        }
        </div>

        @*Filters database results by the latest 60 days*@
        <div class="search-container input-group my-2">
            <form asp-controller="Opportunity" asp-action="Index" class="form-inline mb-3">
                <button value="true" name="date" class="btn btn-primary">Filter by recent (60 days)</button>
            </form>
        </div>


        <a asp-controller="Home" asp-action="VolunteerOpportunityMatches" class="btn btn-primary">View Volunteer Opportunity Matches</a>
        @using (Html.BeginForm())
        {
<button type="submit" class="btn btn-danger my-3" value="reset" name="option">Reset Filters</button>}
    </div>
</div>

</div>